const PptData=[
    {
      "name":'Arabic',
      "img":"/img/client-dashboard/icons-ppt.png",
      "flag":"https://media.peacecoin.io/arabic.png"
    },
    {
      "name":'English',
      "img":"/img/client-dashboard/icons-ppt.png",
      "flag":"https://media.peacecoin.io/american.png"
    },
    {
      "name":'German',
      "img":"/img/client-dashboard/icons-ppt.png",
      "flag":"https://media.peacecoin.io/german.png"
    },
    {
      "name":'French',
      "img":"/img/client-dashboard/icons-ppt.png",
      "flag":"https://media.peacecoin.io/french.png"
    },
    {
      "name":'Italy',
      "img":"/img/client-dashboard/icons-ppt.png",
      "flag":"https://media.peacecoin.io/italine.png"
    },
    {
      "name":'Hindi',
      "img":"/img/client-dashboard/icons-ppt.png",
      "flag":"https://media.peacecoin.io/hindi.png"
    },
    {
      "name":'Hebrew',
      "img":"/img/client-dashboard/icons-ppt.png",
      "flag":"https://media.peacecoin.io/hebrew.png"
    },
    {
      "name":'Chinese',
      "img":"/img/client-dashboard/icons-ppt.png",
      "flag":"https://media.peacecoin.io/chines.png"
    },
    ]
    export default PptData
