import React from 'react'


const WhyUsData = [
    {
        id:"video_1",
        poster:'https://media.peacecoin.io/peaceposter.jpg',
        video_src:'https://s3.us-east-2.amazonaws.com/b.peacecoin.io/sizzle_videos/english.mp4'
    },
    {
        id:"video_2",
        poster:'https://media.peacecoin.io/peaceposter.jpg',
        video_src:'https://s3.us-east-2.amazonaws.com/b.peacecoin.io/sizzle_videos/french.mp4'
    },
    {
        id:"video_3",
        poster:'https://media.peacecoin.io/peaceposter.jpg',
        video_src:'https://s3.us-east-2.amazonaws.com/b.peacecoin.io/sizzle_videos/german.mp4'
    },
    {
        id:"video_4",
        poster:'https://media.peacecoin.io/peaceposter.jpg',
        video_src:'https://s3.us-east-2.amazonaws.com/b.peacecoin.io/sizzle_videos/italian.mp4'
    },
    {
        id:"video_5",
        poster:'https://media.peacecoin.io/peaceposter.jpg',
        video_src:'https://s3.us-east-2.amazonaws.com/b.peacecoin.io/sizzle_videos/japenese.mp4'
    },
    {
        id:"video_6",
        poster:'https://media.peacecoin.io/peaceposter.jpg',
        video_src:'https://s3.us-east-2.amazonaws.com/b.peacecoin.io/sizzle_videos/spanish.mp4'
    },
    {
        id:"video_7",
        poster:'https://media.peacecoin.io/peaceposter.jpg',
        video_src:'https://s3.us-east-2.amazonaws.com/b.peacecoin.io/sizzle_videos/chinese.mp4'
    },
    {
        id:"video_8",
        poster:'https://media.peacecoin.io/peaceposter.jpg',
        video_src:'https://s3.us-east-2.amazonaws.com/b.peacecoin.io/sizzle_videos/hebrew.mp4'
    },
    {
        id:"video_9",
        poster:'https://media.peacecoin.io/peaceposter.jpg',
        video_src:'https://s3.us-east-2.amazonaws.com/b.peacecoin.io/sizzle_videos/arabic.mp4'
    },
    {
        id:"video_10",
        poster:'https://media.peacecoin.io/peaceposter.jpg',
        video_src:'https://s3.us-east-2.amazonaws.com/b.peacecoin.io/sizzle_videos/urdu.mp4'
    },
    {
        id:"video_11",
        poster:'https://media.peacecoin.io/peaceposter.jpg',
        video_src:'https://s3.us-east-2.amazonaws.com/b.peacecoin.io/sizzle_videos/portuges.mp4'
    },
    {
        id:"video_12",
        poster:'https://media.peacecoin.io/peaceposter.jpg',
        video_src:'https://s3.us-east-2.amazonaws.com/b.peacecoin.io/sizzle_videos/hindi.mp4'
    },
    {
        id:"video_13",
        poster:'https://media.peacecoin.io/peaceposter.jpg',
        video_src:'https://s3.us-east-2.amazonaws.com/b.peacecoin.io/sizzle_videos/punjabi.mp4'
    },
    {
        id:"video_14",
        poster:'https://media.peacecoin.io/peaceposter.jpg',
        video_src:'https://s3.us-east-2.amazonaws.com/b.peacecoin.io/sizzle_videos/indo.mp4'
    },
      {
        id:"video_15",
        poster:'https://media.peacecoin.io/peaceposter.jpg',
        video_src:'https://s3.us-east-2.amazonaws.com/b.peacecoin.io/sizzle_videos/russian.mp4'
    },
]
export default WhyUsData;